# -*- coding: utf-8 -*-
"""Colab Embeddings and Graph Data Generation

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OK8SQSeTFS5dfaCcAfiXFxyjV364wmP3

------------------------------------------------------------------------------
WHAT THIS FILE DOES AND DOES NOT PRODUCE
------------------------------------------------------------------------------
Reproduces, via make_graph():
  static/maps/both_figures.json  - the 269-figure map. Section 4's scatter, the
                                   PC1/PC2 the discriminant in section 5 runs on,
                                   and the k=8 links behind the 84.9% homophily
                                   statistic. Note StandardScaler and PCA are both
                                   fit on all 269 figures at once; that is the
                                   caveat section 6 declares.
Reproduces, via compare():
  the three cosine-similarity means in section 3 -- but see the diagonal note on
  compare() below, which tools/build_data.py corrects before publishing them.
Reproduces, via SentenceTransformer:
  the all-MiniLM-L6-v2 title embeddings behind section 10.

Does NOT produce Data/figure_metrics.csv, and therefore does not reproduce any
of section 7's four diagnostics -- clip_similarity (caption agreement),
structural_complexity, gibberish_ratio, repetition. There is no OCR in this file.
Those columns arrive precomputed and their provenance is still open.

The embed_directory() path at the top applies a deviation emphasis
(z_emph = z * norms**alpha, alpha=0.5) and feeds static/maps/figures.json, which
the blog post does not load. No published number depends on that exaggeration.
"""

# Run this in a Colab cell if you haven't already
# !pip install open_clip_torch torch torchvision pillow scikit-learn tqdm

# from google.colab import drive
# drive.mount('/content/drive')

# embed_figures.py

import os
import numpy as np
from PIL import Image
from tqdm import tqdm

import torch
import open_clip
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler

IMAGE_EXTS = (".png", ".jpg", ".jpeg", ".webp", ".tif", ".tiff", ".bmp", ".gif")

def load_model(device="cuda"):
    model, _, preprocess = open_clip.create_model_and_transforms(
        "ViT-B-32", pretrained="laion2b_s34b_b79k"
    )
    model.to(device)
    model.eval()
    return model, preprocess

def embed_directory(image_dir, out_path="fig_embeddings.npz", device=None):
    if device is None:
        device = "cuda" if torch.cuda.is_available() else "cpu"

    model, preprocess = load_model(device)

    embeddings = []
    filenames = []

    with torch.no_grad():
        for fname in tqdm(sorted(os.listdir(image_dir)), desc="Embedding images"):
            if not fname.lower().endswith(IMAGE_EXTS):
                continue

            path = os.path.join(image_dir, fname)
            img = Image.open(path).convert("RGB")
            img_tensor = preprocess(img).unsqueeze(0).to(device)

            feat = model.encode_image(img_tensor)
            feat = feat / feat.norm(dim=-1, keepdim=True)  # unit norm
            embeddings.append(feat.cpu().numpy()[0])
            filenames.append(fname)

    embeddings = np.stack(embeddings)  # (N, D)

    # Center and z-score to highlight deviations from the "average" figure
    scaler = StandardScaler(with_mean=True, with_std=True)
    z = scaler.fit_transform(embeddings)

    # Extra deviation emphasis:
    # scale each vector by (norm)^alpha so outliers get pushed out
    norms = np.linalg.norm(z, axis=1, keepdims=True)  # shape (N, 1)
    alpha = 0.5  # tweak this: higher alpha = more exaggeration
    z_emph = z * (norms ** alpha)

    # Reduce to 3D for initial positions in the graph
    pca = PCA(n_components=3)
    coords3d = pca.fit_transform(z_emph)

    np.savez(
        out_path,
        filenames=np.array(filenames),
        embeddings=embeddings,
        z=z,
        z_emph=z_emph,
        coords3d=coords3d,
    )
    print(f"Saved embeddings to {out_path}")


# build_figure_graph.py

import json
from sklearn.metrics.pairwise import cosine_distances

def build_graph(npz_path="fig_embeddings.npz",
                out_path="figure_graph.json",
                k_neighbors=5):
    data = np.load(npz_path, allow_pickle=True)
    filenames = data["filenames"]
    z_emph = data["z_emph"]
    coords3d = data["coords3d"]

    n = len(filenames)

    # Cosine distance on the deviation-emphasized embeddings
    dist = cosine_distances(z_emph)

    nodes = []
    for i, name in enumerate(filenames):
        deviation = float(np.linalg.norm(z_emph[i]))  # how "weird" this figure is
        nodes.append({
            "id": int(i),
            "name": str(name),
            "deviation": deviation,
            "x": float(coords3d[i, 0]),
            "y": float(coords3d[i, 1]),
            "z": float(coords3d[i, 2]),
        })

    links = []
    for i in range(n):
        # sort by distance, skip self at index 0
        nn_idx = np.argsort(dist[i])[1:k_neighbors + 1]
        for j in nn_idx:
            d = dist[i, j]
            weight = 1.0 / (1e-6 + d)  # larger weight for more similar figures
            links.append({
                "source": int(i),
                "target": int(j),
                "weight": float(weight),
            })

    graph = {"nodes": nodes, "links": links}

    with open(out_path, "w") as f:
        json.dump(graph, f, indent=2)

    print(f"Wrote graph JSON to {out_path}")


# ---------------------------------------------------------------- both sets

def embed_dir(path, model, preprocess, device):
    embeddings = []
    names = []
    with torch.no_grad():
        for f in sorted(os.listdir(path)):
            if not f.lower().endswith(IMAGE_EXTS):
                continue
            p = os.path.join(path, f)
            img = Image.open(p).convert("RGB")
            x = preprocess(img).unsqueeze(0).to(device)
            e = model.encode_image(x)
            e = e / e.norm(dim=-1, keepdim=True)
            embeddings.append(e.cpu().numpy()[0])
            names.append(f)
    return np.array(embeddings), names

def embed_both(generated_dir, real_dir, out="both_embeddings.npz"):
    device = "cuda" if torch.cuda.is_available() else "cpu"
    model, preprocess = load_model(device)

    print("Embedding generated figures")
    gen_emb, gen_names = embed_dir(generated_dir, model, preprocess, device)

    print("Embedding real figures")
    real_emb, real_names = embed_dir(real_dir, model, preprocess, device)

    np.savez(
        out,
        gen_emb=gen_emb,
        real_emb=real_emb,
        gen_names=np.array(gen_names),
        real_names=np.array(real_names)
    )
    print(f"Saved {out}")


from sklearn.metrics.pairwise import cosine_similarity

def compare(npz="both_embeddings.npz"):
    """Mean pairwise cosine similarity within and between the two populations.

    CAUTION -- gg and rr are square self-comparisons, so gg.mean() and rr.mean()
    include each figure's similarity to itself: a diagonal of 1.0 worth 1/n of the
    mean. The cross-group matrix gr has no diagonal. Reported as-is, the two
    within-group numbers are inflated and the cross-group one is not, which is
    exactly the comparison section 3 of the post rests on -- and the smaller real
    set is inflated more (1/113 vs 1/156). tools/build_data.py strips the diagonal
    from these printed values before publishing them; see _offdiag() there.
    """
    d = np.load(npz, allow_pickle=True)
    g = d["gen_emb"]
    r = d["real_emb"]
    g_names = d["gen_names"]
    r_names = d["real_names"]

    # compute similarity matrices
    gg = cosine_similarity(g, g)        # generated to generated
    rr = cosine_similarity(r, r)        # real to real
    gr = cosine_similarity(g, r)        # generated to real

    # compute average similarities (raw; diagonal NOT removed -- see docstring)
    avg_g2r = gr.mean()
    avg_g2g = gg.mean()
    avg_r2r = rr.mean()

    print("Average g to r similarity:", avg_g2r)
    print("Average g to g similarity:", avg_g2g)
    print("Average r to r similarity:", avg_r2r)

    # the same three, over distinct pairs only -- these are what the post publishes
    ng, nr = len(g), len(r)
    print("  off-diagonal g to g:", (avg_g2g * ng * ng - ng) / (ng * ng - ng))
    print("  off-diagonal r to r:", (avg_r2r * nr * nr - nr) / (nr * nr - nr))

    # save everything for visualization
    np.savez(
        "comparison_results.npz",
        gg=gg,
        rr=rr,
        gr=gr,
        g_names=g_names,
        r_names=r_names
    )
    print("Saved comparison_results.npz")


def make_graph(npz_path="both_embeddings.npz", out="both_graph.json", k=8):
    """Produces static/maps/both_figures.json -- the map the post is built on."""
    d = np.load(npz_path, allow_pickle=True)
    g = d["gen_emb"]
    r = d["real_emb"]
    g_names = list(d["gen_names"])
    r_names = list(d["real_names"])

    # merge embeddings and labels
    X = np.concatenate([g, r], axis=0)
    names = g_names + r_names
    labels = ["generated"] * len(g_names) + ["real"] * len(r_names)

    # normalize only (no exaggeration).
    # NOTE: fit on all 269 figures at once, as is the PCA below. Nothing here sees
    # the real/generated label, but the projection has seen the whole corpus --
    # this is the caveat section 6 of the post declares.
    z = StandardScaler().fit_transform(X)

    # reduce to 3D for visualization
    coords = PCA(n_components=3).fit_transform(z)

    # build similarity graph
    dist = cosine_distances(z)
    nodes = []
    links = []

    n = len(names)
    for i in range(n):
        nodes.append({
            "id": i,
            "name": names[i],
            "type": labels[i],
            "x": float(coords[i, 0]),
            "y": float(coords[i, 1]),
            "z": float(coords[i, 2])
        })

        nn = np.argsort(dist[i])[1:k+1]
        for j in nn:
            w = 1.0 / (1e-6 + dist[i, j])
            links.append({
                "source": i,
                "target": int(j),
                "weight": float(w)
            })

    graph = {"nodes": nodes, "links": links}

    with open(out, "w") as f:
        json.dump(graph, f, indent=2)

    print("Wrote", out)


# ------------------------------------------------- title embeddings (section 10)

def semantic_similarity(text1: str, text2: str) -> float:
    """Semantic cosine similarity between two strings using Sentence-BERT."""
    from sentence_transformers import SentenceTransformer
    model = SentenceTransformer("all-MiniLM-L6-v2")  # small, fast, good quality
    embeddings = model.encode([text1, text2])
    return float(cosine_similarity([embeddings[0]], [embeddings[1]])[0][0])


if __name__ == "__main__":
    # Point these at the two figure folders, then run in order.
    GEN = "drive/MyDrive/CVPR ART COMP/CVPR AI Figures"
    REAL = "drive/MyDrive/CVPR ART COMP/Real Figures"

    embed_both(GEN, REAL)
    compare()
    make_graph()   # -> both_graph.json, shipped as static/maps/both_figures.json
